### ISSUE TITLE
Need help config cluster use Redis cluster

### ISSUE THREAD

**Issue by bacnv** [deepstreamIO/deepstream.io-clusternode-redis#4] opened 2020-11-20 04:45 UTC
I can not config Deepstream cluster use Redis cluster.
Can you help me to config ?

 I'm using Deepstream 5 latest on DockerHub.
Thanks bro.

my configs are here:

> clusterNode:
  name: redis
  options:
    nodes:
      - host: ip
        port: 6380
        password: 'password'
      - host: ip
        port: 6381
        password: 'password'
      - host: ip
        port: 6382
        password: 'password'
      - host: ip
        port: 6383
        password: 'password'
      - host: ip
        port: 6384
        password: 'password'
      - host: ip
        port: 6385
        password: 'password'
    maxRedirections: 16
    redisOptions:
       password: 'password'

and

> clusterNode:
  name: redis
  options:
    nodes:
      - host: ip
        port: 6380
      - host: ip
        port: 6381
      - host: ip
        port: 6382
      - host: ip
        port: 6383
      - host: ip
        port: 6384
      - host: ip
        port: 6385
    maxRedirections: 16
    redisOptions:
       password: 'password'

![image](https://user-images.githubusercontent.com/12888672/99760530-7a90e580-2b26-11eb-8d48-2344a5bb653d.png)
![image](https://user-images.githubusercontent.com/12888672/99760595-a318df80-2b26-11eb-99e8-26f568b9dfde.png)

But if i config use redis standalone, it run ok.

> clusterNode:
  name: redis
  options:
      host: ip
      port: 6379
      password: 'password'

**Comment by yasserf** [comment] 2020-11-20 12:39
this repo is for the clustering and not redis cache

To connect to redis cache look at the deepstream.io-cache-redis repo

That being said, in the code it says it supports clustering via:

```
 * To connect to a cluster you can use:
 *
 * {
 *    nodes: [
 *      // Use password "password-for-30001" for 30001
 *      { port: <Number>, password: <String> },
 *      // Don't use password when accessing 30002
 *      { port: <Number>, password: null }
 *      // Other nodes will use "fallback-password"
 *    ],
 *    redisOptions: {
 *      password: 'fallback-password'
 *    }
 * }
```

which does seem pretty correct. Any chance you have any logs when it runs?

**Comment by bacnv** [comment] 2020-11-24 03:42
Thanks @yasserf 
I read tutorial in this link https://deepstream.io/tutorials/plugins/clusternode/redis/

If I config cluster use redis cluster, log error in line 55 redis-connection.ts
REDIS_CONNECTION_ERROR | REDIS error: Error: connect ECONNREFUSED 127.0.0.1:6379 but my redis cluster is not in localhost, it's in a other server.

I don't know Js, but I guess by this code

redis-connection.ts line 23-24
> const nodes = options.nodes
   delete options.nodes

when delete options.node, nodes will be None.

**Comment by yasserf** [comment] 2020-11-24 17:41
That deletes the nodes reference from options but passes it to redis

```
      const nodes = options.nodes <-- holds reference
      delete options.nodes <-- deletes from object
      this.client = new Cluster(nodes, options) as any <-- passes nodes to the cluster
```

Using the config:

```
cache:
  name: redis
  options:
    nodes:
      - host: localhost
        port: 6379
    maxRedirections: 16
    redisOptions:
      dropBufferSupport: true
```

I get the error:

```
REDIS_CACHE | REDIS_CONNECTION_ERROR | REDIS error: ClusterAllFailedError: Failed to refresh slots cache.
```

Which means it does actually try to connect to a cluster. I just don't have a redis cluster setup enabled.

**Comment by bacnv** [comment] 2020-11-25 03:19
I using config and add more option dropBufferSupport

![image](https://user-images.githubusercontent.com/12888672/100178182-fbc0f180-2f05-11eb-9373-0e94ccc9e9f7.png)

I get same old error

![image](https://user-images.githubusercontent.com/12888672/100178331-40e52380-2f06-11eb-9b59-08eca7ca3c9d.png)


I think i will find a way to fix it and use standalone redis first.
thanks @yasserf

**Comment by yasserf** [comment] 2020-11-25 11:34
Cool. I'm going to close this issue as I can't reproduce. If you find out what your issue is let me know.

**Closed by yasserf** 2020-11-25 11:34 UTC
